import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const directory = fileURLToPath(new URL(".", import.meta.url));
const bundlePath = fileURLToPath(new URL("./jev-agent.mjs", import.meta.url));
const checksumPath = `${bundlePath}.sha256`;
const license = await readFile(new URL("./node_modules/@typesafe-ai/sdk/LICENSE", import.meta.url), "utf8");
const banner = `/* Generated by npm run build:repl.\n\nBundled dependency: @typesafe-ai/sdk\n\n${license.trim()}\n*/`;
const result = await build({
	entryPoints: [fileURLToPath(new URL("./repl.ts", import.meta.url))],
	absWorkingDir: directory,
	bundle: true,
	platform: "node",
	format: "esm",
	minify: true,
	legalComments: "none",
	banner: { js: banner },
	write: false,
});
const bundle = result.outputFiles[0].contents;
const checksum = `${createHash("sha256").update(bundle).digest("hex")}  jev-agent.mjs\n`;

if (process.argv.includes("--check")) {
	const [committedBundle, committedChecksum] = await Promise.all([
		readFile(bundlePath),
		readFile(checksumPath, "utf8"),
	]);
	if (!committedBundle.equals(bundle) || committedChecksum !== checksum) {
		throw new Error("REPL bundle is stale; run npm run build:repl");
	}
} else {
	await Promise.all([
		writeFile(bundlePath, bundle),
		writeFile(checksumPath, checksum),
	]);
}
